name: my_flutter_web_app # Changed from my_flutter_web_app_temp
description: "A new Flutter project for Web with Firebase."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  # State Management
  provider: ^6.1.2

  # Utility
  intl: ^0.19.0
  uuid: ^4.3.3

  # Default Cupertino Icons
  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^17.0.0 # Check for latest version
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  jiffy: ^6.3.2
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
